server:
  port: 7090

spring:
  application:
    name: concurrencyLab
  datasource:
    url: jdbc:mysql://localhost:3309/mydb?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
    driver-class-name:  com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql:  true
    open-in-view: false


logging:
  level:
    root: info
    com:
      example:
        springconcurrencylab: debug
    org:
      springframework:
        transaction:
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html     # ?? ??
    operationsSorter: method   # API ?? ?? (method, alpha, etc.)
    tagsSorter: alpha          # ?? ?? ??
    display-request-duration: true # ?? ?? ??
  api-docs:
    path: /v3/api-docs         # API ?? JSON ?? ??